__EAS 503 Final Data Project__
- This project is on the 2010 Energy Usage Data

## last edited 11-14-2017 at group meeting
-also removed "OCCUPIED HOUSING UNITS" as it was a duplicate of "OCCUPIED UNITS"
-exported partitioned dataframes back to .csv files

In [89]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time

data = pd.read_csv('Energy_Usage_2010.csv')
df = pd.DataFrame(data)
df=data.sort_values(['COMMUNITY AREA NAME'])

# Check Shape
print(df.shape)

# Check total NaN count
print("Total NaN's: ",df.isnull().sum().sum())

# Drop unnecessary columns
df2=df.drop(df.columns.to_series()["KWH MEAN 2010":"THERMS SQFT MAXIMUM 2010"],axis=1)
df2=df2.drop("OCCUPIED HOUSING UNITS",axis=1)

# Create Community Area DataFrame to store aggregate Community Area Data, then remove data missing from this.
CMA = df2.loc[df['CENSUS BLOCK'].isnull()]
CMA = CMA.drop(["CENSUS BLOCK","BUILDING TYPE","BUILDING_SUBTYPE"],axis=1)

# Remove 77 rows from main dataframe that were moved to the above CBDF and rows missing KWH data and Total Therm data
df3 = df2.dropna(subset=["CENSUS BLOCK","KWH JANUARY 2010","TOTAL THERMS"], thresh=3)

# Check shape after cleaning
print(df3.shape)

# Check total NaN count after cleaning
print("Total NaN's: ",df3.isnull().sum().sum())

# See what's still missing, we elected to keep the columns missing some Therm data for now
print(df3.isnull().sum())

# Define each community area in each of the 9 districts
FarNorth = ["FarNorth","Rogers Park","West Ridge","Uptown","Lincoln Square","Edison Park","Norwood Park","Jefferson Park","Forest Glen","North Park","Albany Park","O'Hare","Edgewater"]
North = ["North","North Center","Lakeview","Lincoln Park","Avondale","Logan Square"]
Northwest = ["Northwest","Portage Park","Irving Park","Dunning","Montclare","Belmont Cragin","Hermosa"]
Central =["Central","Near North Side","Loop","Near South Side"]
West =["West","Humboldt Park","West Town","Austin","West Garfield Park","East Garfield Park","Near West Side","North Lawndale","South Lawndale","Lower West Side"]
Southwest =["Southwest","Garfield Ridge","Archer Heights","Brighton Park","McKinley Park","New City","West Elsdon","Gage Park","Clearing","West Lawn","Chicago Lawn","West Englewood","Englewood"]
South =["South","Armour Square","Douglas","Oakland","Fuller Park","Grand Boulevard","Kenwood","Washington Park","Hyde Park","Woodlawn","South Shore","Bridgeport","Greater Grand Crossing"]
FarSouthwest=["FarSouthwest","Ashburn","Auburn Gresham","Beverly","Washington Heights","Mount Greenwood","Morgan Park"]
FarSouth =["FarSouth","Chatham","Avalon Park","South Chicago","Burnside","Calumet Heights","Roseland","Pullman","South Deering","East Side","West Pullman","Riverdale","Hegewisch"]

# Concatenate all district lists into single list, initialize empty "dist" data frame 
districts = [FarNorth,North,Northwest,Central,West,Southwest,South,FarSouthwest,FarSouth]
dist=pd.DataFrame(columns=CMA.columns.values)

# Iterate through the districts list and filter the cleaned "df3" data frame to select only sums of requested community areas
for district in districts:
    part = CMA[CMA['COMMUNITY AREA NAME'].isin(district)]
    distsum=part.sum(axis=0)
    dist=dist.append(distsum,ignore_index=True)

# Rename "community area names" to "district"
dist=dist.rename(columns = {'COMMUNITY AREA NAME':'DISTRICT'})

# Apply district names, normalize columns that were averages
i=0
for district in districts:
    dist.iloc[i,0]=districts[i][0]
    dist.iloc[i,[34,35,36,38,40]]=dist.iloc[i,[34,35,36,38,40]]/len(district)
    i+=1

#Export cleaned Census Block, Community Area and District df's back to .csv's
df3.to_csv("Census_Blocks.csv")
CMA.to_csv("Community_Areas.csv")
dist.to_csv("Districts.csv")

(67051, 73)
Total NaN's:  128160
(64807, 44)
Total NaN's:  12580
COMMUNITY AREA NAME                      0
CENSUS BLOCK                             0
BUILDING TYPE                            0
BUILDING_SUBTYPE                         0
KWH JANUARY 2010                         0
KWH FEBRUARY 2010                        0
KWH MARCH 2010                           0
KWH APRIL 2010                           0
KWH MAY 2010                             0
KWH JUNE 2010                            0
KWH JULY 2010                            0
KWH AUGUST 2010                          0
KWH SEPTEMBER 2010                       0
KWH OCTOBER 2010                         0
KWH NOVEMBER 2010                        0
KWH DECEMBER 2010                        0
TOTAL KWH                                0
ELECTRICITY ACCOUNTS                     0
ZERO KWH ACCOUNTS                        0
THERM JANUARY 2010                     862
THERM FEBRUARY 2010                   2848
THERM MARCH 2010                       139
TERM APRIL 2010                        222
THERM MAY 2010                         486
THERM JUNE 2010                        383
THERM JULY 2010                        404
THERM AUGUST 2010                      499
THERM SEPTEMBER 2010                   869
THERM OCTOBER 2010                     328
THERM NOVEMBER 2010                    182
THERM DECEMBER 2010                    189
TOTAL THERMS                             0
GAS ACCOUNTS                             0
KWH TOTAL SQFT                         279
THERMS TOTAL SQFT                      377
TOTAL POPULATION                         7
TOTAL UNITS                              7
AVERAGE STORIES                          0
AVERAGE BUILDING AGE                     0
AVERAGE HOUSESIZE                        7
OCCUPIED UNITS                           7
OCCUPIED UNITS PERCENTAGE             2164
RENTER-OCCUPIED HOUSING UNITS            7
RENTER-OCCUPIED HOUSING PERCENTAGE    2314
dtype: int64

In [90]:
dist

,DISTRICT,KWH JANUARY 2010,KWH FEBRUARY 2010,KWH MARCH 2010,KWH APRIL 2010,KWH MAY 2010,KWH JUNE 2010,KWH JULY 2010,KWH AUGUST 2010,KWH SEPTEMBER 2010,...,THERMS TOTAL SQFT,TOTAL POPULATION,TOTAL UNITS,AVERAGE STORIES,AVERAGE BUILDING AGE,AVERAGE HOUSESIZE,OCCUPIED UNITS,OCCUPIED UNITS PERCENTAGE,RENTER-OCCUPIED HOUSING UNITS,RENTER-OCCUPIED HOUSING PERCENTAGE
0,FarNorth,29327205.0,27435376.0,24620320.0,25557762.0,31107403.0,35995054.0,34673384.0,31424799.0,25910804.0,...,30304977.0,275544.0,135302.0,1.885385,48.870000,485.783846,122102.0,0.840654,76697.0,0.502838
1,North,16743740.0,15952042.0,15212847.0,14858073.0,18398048.0,21627023.0,22022564.0,20754463.0,16946229.0,...,24566871.0,168914.0,98781.0,1.630000,52.345000,641.791667,88885.0,0.733883,59733.0,0.544050
2,Northwest,9273820.0,9890460.0,9213931.0,9439090.0,11457836.0,13262148.0,13206942.0,12634981.0,10492364.0,...,12138334.0,121048.0,47975.0,1.304286,47.455714,727.765714,43437.0,0.765714,22785.0,0.454800
3,Central,92176700.0,88312203.0,81144816.0,76664787.0,87890647.0,93960136.0,98869302.0,94971629.0,87996743.0,...,89745126.0,90832.0,67787.0,7.525000,29.532500,126.137500,56941.0,0.630850,38778.0,0.545500
4,West,66502823.0,68544448.0,69405574.0,68167050.0,83401677.0,90234345.0,96359615.0,91814388.0,76904992.0,...,53746033.0,251776.0,101618.0,1.572000,51.619000,911.846000,83829.0,0.724840,59323.0,0.652830
5,Southwest,22899439.0,22912491.0,21305965.0,21534806.0,23517796.0,26524076.0,26266403.0,26755466.0,23150960.0,...,21425746.0,159516.0,59493.0,1.342308,53.109231,736.409231,49149.0,0.798031,27138.0,0.468169
6,South,43668680.0,45296528.0,43855117.0,44653869.0,51342826.0,60055699.0,62012587.0,59901888.0,51625982.0,...,25499737.0,189588.0,99758.0,2.034615,47.063846,373.296154,83371.0,0.773915,62227.0,0.691538
7,FarSouthwest,7924165.0,7714984.0,7057589.0,7125352.0,8610379.0,9467855.0,9594286.0,8539945.0,7177595.0,...,7498120.0,74599.0,32189.0,1.232857,45.502857,529.997143,28403.0,0.769971,11743.0,0.317371
8,FarSouth,28248072.0,32219461.0,29238117.0,30275951.0,30381776.0,33527469.0,34440546.0,30801218.0,29693804.0,...,20742601.0,104219.0,48309.0,1.314615,51.481538,487.840769,39511.0,0.755262,22181.0,0.471831